import type { Content } from './types';

export const mockContents: Content[] = [
  {
    id: '1',
    title: 'Cosmic Odyssey',
    description: 'A journey through the cosmos that challenges our understanding of time and space.',
    releaseYear: 2023,
    duration: 142,
    thumbnailUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHNwYWNlfGVufDB8fDB8fHww',
    videoUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
    trailerUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
    type: 'movie',
    genres: ['Sci-Fi', 'Adventure', 'Drama'],
    cast: ['Emma Stone', 'Ryan Gosling', 'Idris Elba'],
    rating: 4.8
  },
  {
    id: '2',
    title: 'Midnight Shadows',
    description: 'A detective uncovers a conspiracy that threatens to unravel the fabric of society.',
    releaseYear: 2022,
    duration: 118,
    thumbnailUrl: 'https://images.unsplash.com/photo-1478760329108-5c128db06a91?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8ZGFya3xlbnwwfHwwfHx8MA%3D%3D',
    videoUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
    trailerUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
    type: 'movie',
    genres: ['Thriller', 'Mystery', 'Crime'],
    cast: ['Denzel Washington', 'Viola Davis', 'Michael B. Jordan'],
    rating: 4.5
  },
  {
    id: '3',
    title: 'Eternal Spring',
    description: 'A heartwarming tale of love, loss, and redemption set against the backdrop of rural Japan.',
    releaseYear: 2023,
    duration: 125,
    thumbnailUrl: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGphcGFufGVufDB8fDB8fHww',
    videoUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
    trailerUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
    type: 'movie',
    genres: ['Drama', 'Romance'],
    cast: ['Saoirse Ronan', 'Timothée Chalamet', 'Florence Pugh'],
    rating: 4.7
  },
  {
    id: '4',
    title: 'Digital Frontier',
    description: 'A tech genius creates an AI that begins to question its own existence and purpose.',
    releaseYear: 2021,
    duration: 133,
    thumbnailUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8dGVjaHxlbnwwfHwwfHx8MA%3D%3D',
    videoUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
    trailerUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
    type: 'movie',
    genres: ['Sci-Fi', 'Thriller'],
    cast: ['Oscar Isaac', 'Alicia Vikander', 'Domhnall Gleeson'],
    rating: 4.6
  },
  {
    id: '5',
    title: 'Kingdom of Shadows',
    description: 'An epic fantasy series where ancient kingdoms battle for control of a magical realm.',
    releaseYear: 2022,
    duration: 60,
    thumbnailUrl: 'https://images.unsplash.com/photo-1515896769750-31548aa180ed?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fGZhbnRhc3l8ZW58MHx8MHx8fDA%3D',
    videoUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
    trailerUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
    type: 'show',
    genres: ['Fantasy', 'Adventure', 'Action'],
    cast: ['Kit Harington', 'Emilia Clarke', 'Peter Dinklage'],
    rating: 4.9
  },
  {
    id: '6',
    title: 'Urban Legends',
    description: 'A documentary series exploring the truth behind famous urban myths and legends.',
    releaseYear: 2023,
    duration: 45,
    thumbnailUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bXlzdGVyeXxlbnwwfHwwfHx8MA%3D%3D',
    videoUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
    trailerUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
    type: 'show',
    genres: ['Documentary', 'Mystery'],
    cast: ['Morgan Freeman', 'David Attenborough'],
    rating: 4.3
  },
  {
    id: '7',
    title: 'Culinary Masters',
    description: 'Top chefs compete to create extraordinary dishes under extreme pressure.',
    releaseYear: 2022,
    duration: 55,
    thumbnailUrl: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2hlZnxlbnwwfHwwfHx8MA%3D%3D',
    videoUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
    trailerUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
    type: 'show',
    genres: ['Reality', 'Food'],
    cast: ['Gordon Ramsay', 'Jamie Oliver'],
    rating: 4.2
  },
  {
    id: '8',
    title: 'Quantum Paradox',
    description: 'Scientists discover a parallel universe that threatens to collide with our own.',
    releaseYear: 2023,
    duration: 138,
    thumbnailUrl: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cXVhbnR1bXxlbnwwfHwwfHx8MA%3D%3D',
    videoUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
    trailerUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
    type: 'movie',
    genres: ['Sci-Fi', 'Action'],
    cast: ['Scarlett Johansson', 'Robert Downey Jr.', 'Chris Evans'],
    rating: 4.7
  },
  {
    id: '9',
    title: 'Whispers in the Dark',
    description: 'A psychological horror about a family that moves into a house with a disturbing past.',
    releaseYear: 2021,
    duration: 112,
    thumbnailUrl: 'https://images.unsplash.com/photo-1555354921-86fefcb1b761?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGhvcnJvcnxlbnwwfHwwfHx8MA%3D%3D',
    videoUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
    trailerUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
    type: 'movie',
    genres: ['Horror', 'Thriller'],
    cast: ['Toni Collette', 'Gabriel Byrne', 'Alex Wolff'],
    rating: 4.4
  },
  {
    id: '10',
    title: 'Legal Eagles',
    description: 'A legal drama following ambitious attorneys at a prestigious law firm in New York.',
    releaseYear: 2022,
    duration: 50,
    thumbnailUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8bGF3eWVyfGVufDB8fDB8fHww',
    videoUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
    trailerUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
    type: 'show',
    genres: ['Drama', 'Crime'],
    cast: ['Gabriel Macht', 'Sarah Rafferty', 'Rick Hoffman'],
    rating: 4.5
  },
  {
    id: '11',
    title: 'Wilderness Survival',
    description: 'A reality show where contestants must survive in the harshest environments on Earth.',
    releaseYear: 2023,
    duration: 48,
    thumbnailUrl: 'https://images.unsplash.com/photo-1414016642750-7fdd78dc33d9?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8d2lsZGVybmVzc3xlbnwwfHwwfHx8MA%3D%3D',
    videoUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
    trailerUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
    type: 'show',
    genres: ['Reality', 'Adventure'],
    cast: ['Bear Grylls', 'Les Stroud'],
    rating: 4.1
  },
  {
    id: '12',
    title: 'Historical Echoes',
    description: 'A period drama set during the Renaissance, following the rise of a powerful banking family.',
    releaseYear: 2021,
    duration: 58,
    thumbnailUrl: 'https://images.unsplash.com/photo-1599946347371-68eb71b16afc?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8cmVuYWlzc2FuY2V8ZW58MHx8MHx8fDA%3D',
    videoUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
    trailerUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
    type: 'show',
    genres: ['Historical', 'Drama'],
    cast: ['Jeremy Irons', 'François Arnaud', 'Holliday Grainger'],
    rating: 4.6
  }
];

export const allGenres = [
  'Action', 'Adventure', 'Comedy', 'Crime', 'Documentary', 
  'Drama', 'Fantasy', 'Food', 'Historical', 'Horror', 
  'Mystery', 'Reality', 'Romance', 'Sci-Fi', 'Thriller'
];